/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119381-gfcc562693e-20250428"
#endif /* AVUTIL_FFVERSION_H */
